routes/web.php
<?php

use App\Http\Controllers\PageController;
use App\Http\Controllers\PersonasController;
use App\Http\Controllers\MedicamentosController;
use App\Http\Controllers\PersonaMedicamentoController;
use App\Models\Persona_Medicamento;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PersonasController::class,'index']);
//Route::get('medicamentos',[PageController::class,'medicamentos'])->name('medicamentos');
Route::resource('personas',PersonasController::class);
Route::resource('medicamentos',MedicamentosController::class);
Route::resource('persona_medicamento',PersonaMedicamentoController::class);
Route::get('persona_medicamneto/busquedaDni',[PersonaMedicamentoController::class, 'busquedaDni'])->name('busquedaDni');
Route::get('persona_medicamneto/busquedaMedicamento',[PersonaMedicamentoController::class, 'busquedaMedicamento'])->name('busquedaMedicamento');

app/Models/Persona_Medicamento.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Persona_Medicamento extends Model
{
    use HasFactory;
    protected $fillable = ['observaciones','persona_id','medicamento_id'];
    public function personas(){
        return $this->belongsTo(Personas::class,'persona_id','id');
    }
    public function medicamentos(){
        return $this->belongsTo(Medicamentos::class,'medicamento_id','id');
    }
}

app/Http/Controllers/PersonaMedicamentoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Persona_Medicamento;
use Illuminate\Http\Request;
use App\Models\Personas;
use App\Models\Medicamentos;

class PersonaMedicamentoController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $persona_medicamento = Persona_Medicamento::all();
        $personas = Personas::all();
        $medicamentos = Medicamentos::all();

        return view('persona_medicamento.persona_medicamento',
        ['persona_medicamento'=>$persona_medicamento,'personas'=>$personas,'medicamentos'=>$medicamentos]);
    }
    public function busquedaDni(Request $request){
        $persona = $request['busqueda'];
        $personas = Personas::all();
        $medicamentos = Medicamentos::all();
        //$consulta = Persona_medicamento::join('personas','persona_id','personas.id')->where('dni',$personas)->get();
        $consulta = Persona_medicamento::join('personas','persona_id','personas.id')->where('dni',$persona)->get();
        return view('persona_medicamento.persona_medicamento',
        ['persona_medicamento'=>$consulta,'personas'=>$personas,'medicamentos'=>$medicamentos]);
    }
    public function busquedaMedicamento(Request $request){
        $medicamento = $request['busqueda'];
        $personas = Personas::all();
        $medicamentos = Medicamentos::all();
        $consulta = Persona_medicamento::whereHas('medicamentos', function($query) use ($medicamento) {
            $query->where('nombre_comercial','LIKE','%'. $medicamento .'%');
        })->get();
        return view('persona_medicamento.persona_medicamento',
        ['persona_medicamento'=>$consulta,'personas'=>$personas,'medicamentos'=>$medicamentos]);
        
        
    }
    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $prescripciones = new Persona_Medicamento($request->only(['persona_id','medicamento_id','observaciones']));
        $prescripciones->saveOrFail();
        return redirect()->route('persona_medicamento.index');
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $persona_medicamento = Persona_Medicamento::find($id);
        $personas = Personas::all();
        $medicamentos = Medicamentos::all();
        return view('persona_medicamento.editPrescripcion',
        ['persona_medicamento'=>$persona_medicamento,'personas'=>$personas,'medicamentos'=>$medicamentos]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $persona_medicamento = Persona_Medicamento::find($id);
        $persona_medicamento->fill($request->only(['persona_id','medicamento_id','observaciones']))->saveOrFail();
        return redirect()->route('persona_medicamento.show', ['persona_medicamento'=>$persona_medicamento]);

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $persona_medicamento = Persona_Medicamento::find($id);
        $persona_medicamento->delete();
        return redirect()->route('persona_medicamento.index');
    }
    
}

resources/views/persona_medicamento/_formAddPrescripcion.blade.php
<div class="modal fade modal-lg" id="agregar_prescripcion" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="agregar_persona" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="agregar_prescripcion">Agregar prescripcion</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{route('persona_medicamento.store')}}" method="POST">
            @csrf
            <div class="row text-center justify-content-center">
                <div class="col-6">
                    <label class="form-label" for="persona_id">Persona</label>
                    <select class="form-select" name="persona_id">
                        @foreach($personas as $value)
                            <option value="{{$value->id}}">{{$value->nombre}} {{$value->apellido}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="row text-center justify-content-center">
                <div class="col-6 m-2">
                    <label class="form-label" for="medicamento_id">Medicamento</label>
                    <select class="form-select" name="medicamento_id">
                        @foreach($medicamentos as $medicamento)
                            <option value="{{$medicamento->id}}">{{$medicamento->nombre_comercial}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="row text-center justify-content-center">
                <div class="col-6 m-2">
                    <label class="form-label" for="observaciones">Observaciones</label>
                    <input name="observaciones" type="text" class="form-control" placeholder="observaciones" required>
                </div>
            </div>
                <button type="button btn btn-lg" class="btn btn-primary m-3">Agregar</button>
        </form>
      </div>
      
    </div>
  </div>
</div>

resources/views/persona_medicamento/editPrescripcion.blade.php
@extends('template.templateHead')
@section('body')
<div class="container">
    <div class="row">
        <div class="col-12">
           
            <div class="card m-5">
                <div class="card-body">
                    <div class="card-title h1 text-center m-4">Editar Prescripcion</div>
                    <form action="{{route('persona_medicamento.update',[$persona_medicamento])}}" method="POST">
                        @method('PATCH')
                        @csrf
                        <div class="row text-center justify-content-center">
                            <div class="col-6">
                                <label class="form-label" for="persona_id">Persona</label>
                                <select class="form-select" name="persona_id">
                                    @foreach($personas as $value)
                                        <option value="{{$value->id}}" 
                                        @if ($value->id == $persona_medicamento->persona_id) selected @endif
                                        >{{$value->nombre}} {{$value->apellido}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="row text-center justify-content-center">
                            <div class="col-6 m-2">
                                <label class="form-label" for="medicamento_id">Medicamento</label>
                                <select class="form-select" name="medicamento_id">
                                    
                                    @foreach($medicamentos as $medicamento)
                                        <option value="{{$medicamento->id}}" 
                                        @if ($medicamento->id == $persona_medicamento->medicamento_id) selected @endif >
                                        {{$medicamento->nombre_comercial}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="row text-center justify-content-center">
                            <div class="col-6 m-2">
                                <label class="form-label" for="observaciones">Observaciones</label>
                                <input name="observaciones" type="text" class="form-control" 
                                placeholder="observaciones" value="{{$persona_medicamento->observaciones}}" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 justify-content-center text-center align-items-center">
                                <input type="submit" class="btn btn-primary btn-lg" value="Modificar">
                            </div>
                        </div>
                    </form>
                    <div class="row justify-content-center text-center align-items-center m-2">
                            <div class="col-4 ">
                                <a href="{{route('persona_medicamento.index')}}"><button type="button" class="btn btn-primary btn-xs">Atrás</button></a>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>
@endsection

resources/views/persona_medicamento/persona_medicamento.blade.php
@extends('../template/template')
@section('agregar')
<button class="btn btn-success btn-lg" id="btnPersona" data-bs-toggle="modal" data-bs-target="#agregar_prescripcion">Agregar Prescripción<i class="mx-1 fa-solid fa-circle-plus"></i></button>
@endsection
@section('buscador')
    <form action="{{route('busquedaDni')}}" method="GET">
        <div class="row">
            <div class="col-xl-6">
                <input type="text" name="busqueda" class="form-control" placeholder="filtrar por dni">
            </div>
            <div class="col-xl-1">
                <button class="button btn btn-success">Buscar</button>
            </div>
        </div>
    </form>
    <form action="{{route('busquedaMedicamento')}}" method="GET" class="mt-2">
        <div class="row">
            <div class="col-xl-6">
                <input type="text" name="busqueda" class="form-control" placeholder="filtrar medicamento">
            </div>
            <div class="col-xl-1">
                <button class="button btn btn-success">Buscar</button>
            </div>
        </div>
    </form>
@endsection
@section('tabla')
    <th>
        <tr class="table-dark">
            <td>id</td>
            <td>Nombre</td>
            <td>Apellido</td>
            <td>Dni</td>
            <td>Medicamento</td>
            <td>Observaciones</td>
            <td>Fecha de prescripcion</td>
            <td>Editar</td>
            <td>Eliminar</td>
        </tr>
    </th>

@include('persona_medicamento._formAddPrescripcion')
@endsection
@section('cuerpo_tabla')
    @foreach($persona_medicamento as $value)
        <tr>
            <td>{{$value->id}}</td>
            <td>{{$value->personas->nombre}}</td>
            <td>{{$value->personas->apellido}}</td>
            <td>{{$value->personas->dni}}</td>
            <td>{{$value->medicamentos->nombre_comercial}}</td>
            <td>{{$value->observaciones}}</td>
            <td>{{$value->created_at}}</td>
            <td>
                <a href="{{ route('persona_medicamento.show',[$value])}}"><button class="mx-2 btn btn-info border-dark"><i class="fa-regular fa-pen-to-square"></i></button></a>
            </td>
            <td>
                <form action="{{ route('persona_medicamento.destroy',[$value]) }}" method="POST" >
                    @method('delete')
                    @csrf
                    <button class="mx-2 btn btn-danger border-dark"><i class="fa-sharp fa-solid fa-trash"></i></button>
                </form>
            </td>
        </tr>
    @endforeach
    
@endsection