routes/web.php
<?php

use App\Http\Controllers\PageController;
use App\Http\Controllers\PersonasController;
use App\Http\Controllers\MedicamentosController;
use App\Http\Controllers\PersonaMedicamentoController;
use App\Models\Persona_Medicamento;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PersonasController::class,'index']);
//Route::get('medicamentos',[PageController::class,'medicamentos'])->name('medicamentos');
Route::resource('personas',PersonasController::class);
Route::resource('medicamentos',MedicamentosController::class);
Route::resource('persona_medicamento',PersonaMedicamentoController::class);
Route::get('persona_medicamneto/busquedaDni',[PersonaMedicamentoController::class, 'busquedaDni'])->name('busquedaDni');
Route::get('persona_medicamneto/busquedaMedicamento',[PersonaMedicamentoController::class, 'busquedaMedicamento'])->name('busquedaMedicamento');

app/Models/Medicamentos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Medicamentos extends Model
{
    use HasFactory;
    protected $fillable = ['nombre_comercial'];
}

app/Http/Controllers/MedicamentosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Medicamentos;
use Illuminate\Validation\Rule;

class MedicamentosController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $medicamentos = Medicamentos::all();
        return view('medicamentos.medicamentos',['medicamentos'=>$medicamentos]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $medicamentos = new Medicamentos($request->input()); //toma todos los inputs para guardarlos

        $request->validate([
            'nombre_comercial'=>'unique:medicamentos,nombre_comercial'
        ],[
            'nombre_comercial.unique'=>'No pueden haber medicamentos iguales, campo duplicado'
        ]);
        
        $medicamentos->saveOrFail();
        return redirect()->route('medicamentos.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $medicamento = Medicamentos::find($id);
        return view('medicamentos.editMed',['medicamento'=>$medicamento]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $medicamento = Medicamentos::find($id);
        $request->validate([
            'nombre_comercial' => [
                'required',
                'string',
                'max:255',
                Rule::unique('medicamentos')->ignore($medicamento->id),
            ]
        ]);
        $medicamento->fill($request->input())->saveOrFail();
        return redirect()->route('medicamentos.show',['medicamento'=>$medicamento]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $medicamento = Medicamentos::find($id);
        $medicamento->delete();
        return redirect()->route('medicamentos.index');
    }
}

resources/views/medicamentos/_formAddMed.blade.php
<div class="modal fade modal-lg" id="agregar_medicamento" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="agregar_persona" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="agregar_medicamento">Agregar Medicamento</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{route('medicamentos.store')}}" method="POST">
            @csrf
            <div class="row text-center justify-content-center">
                <div class="col-6">
                    <label class="form-label" for="nombre_comercial">Nombre comercial</label>
                    <input name="nombre_comercial" type="text" class="form-control" placeholder="Nombre comercial" required>
                </div>
            </div>
                <button type="button btn btn-lg" class="btn btn-primary m-3">Agregar</button>
        </form>
      </div>
      
    </div>
  </div>
</div>

resources/views/medicamentos/editMed.blade.php
@extends('template.templateHead')
@section('body')
<div class="container">
    <div class="row">
        <div class="col-12">
           
            <div class="card m-5">
                <div class="card-body">
                    <div class="card-title h1 text-center m-4">Editar medicamento</div>
                    @error('nombre_comercial')
                        <div class="alert alert-danger" role="alert">
                            {{$message}} 
                        </div>
                    @enderror
                    <form action="{{route('medicamentos.update',[$medicamento])}}" method="POST">
                        @method('PATCH')
                        @csrf
                        @csrf
                        <div class="row text-center justify-content-center">
                            <div class="col-6">
                                <label class="form-label" for="nombre_comercial">Nombre comercial</label>
                                <input name="nombre_comercial" type="text" class="form-control" placeholder="Nombre comercial" value="{{$medicamento->nombre_comercial}}" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 justify-content-center text-center align-items-center m-2">
                                <input type="submit" class="btn btn-primary btn-lg" value="Modificar">
                            </div>
                    </form>
                    <div class="row justify-content-center text-center align-items-center m-2">
                            <div class="col-4 ">
                                <a href="{{route('medicamentos.index')}}"><button type="button" class="btn btn-primary btn-xs">Atrás</button></a>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>
@endsection

resources/views/medicamentos/medicamentos.blade.php
@extends('../template/template')
@section('agregar')
<button class="btn btn-success btn-lg" data-bs-toggle="modal" data-bs-target="#agregar_medicamento" id="btnMedicamento">
Agregar Medicamento<i class="mx-1 fa-solid fa-circle-plus"></i></button>
@endsection
@section('error')
    @error('nombre_comercial')
        <div class="alert alert-danger" role="alert">
            {{$message}} 
        </div>
    @enderror
@endsection
@section('tabla')
    <th>
        <tr class="table-dark">
            <td>id</td>
            <td>Nombre comercial</td>
            <td>Editar</td>
            <td>Eliminar</td>
        </tr>
    </th>
@endsection
@section('cuerpo_tabla')
    @foreach($medicamentos as $value)
        <tr>
            <td>{{$value->id}}</td>
            <td>{{$value->nombre_comercial}}</td>
            <td><a href="{{route('medicamentos.show',[$value])}}"><button class="mx-2 btn btn-info border-dark"><i class="fa-regular fa-pen-to-square"></i></button></a></td>
            <td>
                <form action="{{ route('medicamentos.destroy',[$value]) }}" method="POST" >
                    @method('delete')
                    @csrf
                    <button class="mx-2 btn btn-danger border-dark"><i class="fa-sharp fa-solid fa-trash"></i></button>
                </form>
            </td>
        </tr>
    @endforeach
@include('medicamentos._formAddMed')
@endsection